id: P000447
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W6472
  title: ཆོས་བཤད་གཞན་ཕན་ཟླ་བ།
  author: ''
  volumes:
    51cb387adf1c4e46b344d317113defc5:
      image_group_id: I1KG17043
      title: Volume 1 of chos bshad gzhan phan zla ba/
      volume_number: 1
      total_pages: 327
      base_file: v001.txt
